# spring通用配置
spring:
  application:
    name: k8s-saas
  mvc:
    servlet:
      load-on-startup: 1
  profiles:
    active: local


  datasource:
    url: jdbc:mysql://3.26.202.232:3306/biz_center?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: biz_center
    password: biz_center
    driverClassName: com.mysql.cj.jdbc.Driver

    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: mysql-pool
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1


mybatis:
  mapper-locations: classpath:mapper/*.xml
  checkConfigLocation: true


sa-token:
  token-name: satoken
  # token validation, default 30 days, seconds
  timeout: 2592000
  # token active frequency, -1 no limits, seconds
  active-timeout: -1
  # allow login at the same time
  is-concurrent: true
  # many people login the same account, whether share the token
  is-share: true
  # token style（uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  is-log: true


# 服务配置
server:
  port: 30489
  servlet:
    context-path: /k8s-saas
